# Generated by Django 5.0.6 on 2024-07-04 17:32

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "unique_key",
                    models.CharField(
                        default=shortuuid.main.ShortUUID.uuid,
                        max_length=22,
                        unique=True,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="studying_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        related_name="teaching_courses", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("tasks", models.ManyToManyField(blank=True, to="course_service.task")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
