# Generated by Django 5.0.6 on 2024-07-04 18:33

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="unique_key",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True
            ),
        ),
    ]
