# Generated by Django 5.0.6 on 2024-10-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_service", "0002_course_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="color",
            field=models.CharField(
                choices=[
                    ("#A6DCEF", "secondary-100"),
                    ("#77D99F", "secondary-200"),
                    ("#FDB7AA", "secondary-300"),
                    ("#D2ADE6", "secondary-400"),
                    ("#F9E783", "primary-100"),
                ],
                default="secondary-400",
            ),
        ),
    ]
