# Generated by Django 5.0.6 on 2024-07-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_service", "0002_alter_course_unique_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="unique_key",
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
