# Generated by Django 5.0.6 on 2024-07-05 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_service", "0003_alter_course_unique_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="teaching_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="unique_key",
            field=models.CharField(blank=True, max_length=22, unique=True),
        ),
    ]
