# Generated by Django 5.0.6 on 2024-07-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_service", "0005_alter_course_options_course_created_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-created_date", "name"]},
        ),
        migrations.AlterField(
            model_name="course",
            name="unique_key",
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
