# Generated by Django 5.0.6 on 2024-07-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_service", "0006_alter_course_options_alter_course_unique_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="unique_key",
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
