# Generated by Django 5.0.6 on 2024-07-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_service", "0009_alter_course_unique_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="unique_key",
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
