# Generated by Django 5.0.6 on 2024-07-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_service", "0010_alter_course_unique_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="tasks",
        ),
    ]
