# Generated by Django 5.0.6 on 2024-07-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_service", "0011_remove_course_tasks"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
