# Generated by Django 5.0.6 on 2024-07-19 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_of_task",
                    models.IntegerField(
                        choices=[
                            (1, "Theoretical task"),
                            (2, "Practical task"),
                            (3, "Control task"),
                            (4, "Another task"),
                        ]
                    ),
                ),
                ("topic", models.CharField(max_length=150)),
                ("additionally", models.TextField(blank=True)),
                ("answer_link", models.URLField(blank=True)),
                ("answer_file", models.FileField(blank=True, upload_to="uploads/")),
                ("answer_image", models.ImageField(blank=True, upload_to="images/")),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "No rating!"),
                            (5, "5-points"),
                            (12, "12-points"),
                            (100, "100-points"),
                        ]
                    ),
                ),
                ("note", models.IntegerField(blank=True, null=True)),
                (
                    "for_whom",
                    models.IntegerField(
                        choices=[(1, "All students"), (2, "Select students")]
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="course_service.course",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="doing_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
