# Generated by Django 5.0.6 on 2024-07-20 16:05

import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="answer_file",
        ),
        migrations.RemoveField(
            model_name="task",
            name="answer_image",
        ),
        migrations.AddField(
            model_name="task",
            name="task_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="answer_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AnswerFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=user.models.movie_image_file_path)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_files",
                        to="task_service.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnswerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=user.models.movie_image_file_path),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_images",
                        to="task_service.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=user.models.movie_image_file_path)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_files",
                        to="task_service.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=user.models.movie_image_file_path),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_images",
                        to="task_service.task",
                    ),
                ),
            ],
        ),
    ]
