# Generated by Django 5.0.6 on 2024-07-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="note",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
