# Generated by Django 5.0.6 on 2024-07-20 17:48

import task_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "task_service",
            "0003_remove_task_answer_link_remove_task_note_answer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerfile",
            name="file",
            field=models.FileField(upload_to=task_service.models.file_path),
        ),
        migrations.AlterField(
            model_name="answerimage",
            name="image",
            field=models.ImageField(upload_to=task_service.models.image_path),
        ),
        migrations.AlterField(
            model_name="taskfile",
            name="file",
            field=models.FileField(upload_to=task_service.models.file_path),
        ),
        migrations.AlterField(
            model_name="taskimage",
            name="image",
            field=models.ImageField(upload_to=task_service.models.image_path),
        ),
    ]
