# Generated by Django 5.0.6 on 2024-07-20 17:48

import task_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "task_service",
            "0003_remove_task_answer_link_remove_task_note_answer_and_more",
        ),
    ]

    operations = [

    ]
