# Generated by Django 5.0.6 on 2024-07-23 12:19

import task_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_service", "0005_learningfile_remove_answerimage_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningfile",
            name="file",
            field=models.FileField(upload_to=task_service.models.media_path),
        ),
    ]
