# Generated by Django 5.0.6 on 2024-07-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_service", "0006_alter_learningfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningfile",
            name="model",
            field=models.CharField(
                choices=[("Task", "Task"), ("Answer", "Answer")], max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="learningfile",
            name="type",
            field=models.CharField(
                choices=[("file", "file"), ("image", "image")], max_length=30
            ),
        ),
    ]
