# Generated by Django 5.0.6 on 2024-07-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_service", "0007_alter_learningfile_model_alter_learningfile_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="status",
            field=models.BooleanField(
                choices=[(True, "Done"), (False, "Not Done")], default="Done"
            ),
        ),
    ]
