# Generated by Django 5.0.6 on 2024-07-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_service", "0007_alter_learningfile_model_alter_learningfile_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="status",
            field=models.CharField(
                choices=[("Done", "Done"), ("Not Done", "Not Done")], default="Done"
            ),
        ),
    ]
