# Generated by Django 5.0.6 on 2024-07-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_service", "0008_answer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="status",
            field=models.CharField(
                choices=[("Done", "Done"), ("Not Done", "Not Done")], default="Not Done"
            ),
        ),
    ]
