# Generated by Django 5.0.6 on 2024-06-29 13:15

import user.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirmation_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="media/default_user_image/pngtree-anonymous-user-unidentified-contact-avatar-png-image_4816655.png",
                null=True,
                upload_to=user.models.movie_image_file_path,
            ),
        ),
    ]
