# Generated by Django 5.0.6 on 2024-07-04 18:33

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="media/default_user_image/pngtree-anonymous-user-unidentified-contact-avatar-png-image_4816655.png",
                null=True,
                upload_to=user.models.movie_image_file_path,
            ),
        ),
    ]
