# Generated by Django 5.0.6 on 2024-06-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_email_confirmation_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_confirmation_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_email_confirmed",
        ),
    ]
